# Generated by Django 5.2.8 on 2025-11-12 19:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aeronave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricula', models.CharField(max_length=100)),
                ('tipo_aeronave', models.CharField(max_length=100)),
                ('capacidad_kg', models.IntegerField(default=0)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Carga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peso', models.IntegerField()),
                ('tipo', models.CharField(max_length=100)),
                ('valor', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(max_length=100)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Conductor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('rut', models.CharField(max_length=100)),
                ('licencia', models.CharField(max_length=100)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Piloto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('rut', models.CharField(max_length=100)),
                ('certificacion', models.CharField(max_length=100)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ruta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origen', models.CharField(max_length=500)),
                ('destino', models.CharField(max_length=500)),
                ('tipo_transporte', models.CharField(choices=[('T', 'TERRESTRE'), ('A', 'AEREO')], max_length=100)),
                ('distancia_km', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patente', models.CharField(max_length=100)),
                ('tipo_vehiculo', models.CharField(max_length=100)),
                ('capacidad_kg', models.IntegerField()),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Despacho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_despacho', models.DateField()),
                ('estado', models.CharField(choices=[('ER', 'EN RUTA'), ('E', 'ENTREGADO'), ('P', 'PENDIENTE')], max_length=50)),
                ('costo_envio', models.IntegerField()),
                ('aeronave_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='despacho', to='transporte.aeronave')),
                ('carga_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='despacho', to='transporte.carga')),
                ('cliente_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='despacho', to='transporte.cliente')),
                ('conductor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='despacho', to='transporte.conductor')),
                ('piloto_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='despacho', to='transporte.piloto')),
                ('ruta_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='despacho', to='transporte.ruta')),
                ('vehiculo_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='despacho', to='transporte.vehiculo')),
            ],
        ),
    ]
