# Generated by Django 5.2.8 on 2025-11-17 21:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transporte', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='despacho',
            name='aeronave_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='despacho', to='transporte.aeronave'),
        ),
        migrations.AlterField(
            model_name='despacho',
            name='conductor_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='despacho', to='transporte.conductor'),
        ),
        migrations.AlterField(
            model_name='despacho',
            name='piloto_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='despacho', to='transporte.piloto'),
        ),
        migrations.AlterField(
            model_name='despacho',
            name='vehiculo_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='despacho', to='transporte.vehiculo'),
        ),
    ]
