# Generated by Django 5.2.8 on 2025-11-17 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transporte', '0002_alter_despacho_aeronave_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carga',
            old_name='cliente_id',
            new_name='cliente',
        ),
        migrations.RenameField(
            model_name='despacho',
            old_name='aeronave_id',
            new_name='aeronave',
        ),
        migrations.RenameField(
            model_name='despacho',
            old_name='carga_id',
            new_name='carga',
        ),
        migrations.RenameField(
            model_name='despacho',
            old_name='conductor_id',
            new_name='conductor',
        ),
        migrations.RenameField(
            model_name='despacho',
            old_name='piloto_id',
            new_name='piloto',
        ),
        migrations.RenameField(
            model_name='despacho',
            old_name='ruta_id',
            new_name='ruta',
        ),
        migrations.RenameField(
            model_name='despacho',
            old_name='vehiculo_id',
            new_name='vehiculo',
        ),
    ]
