# Generated by Django 5.2.8 on 2025-11-17 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transporte', '0003_rename_cliente_id_carga_cliente_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carga',
            old_name='cliente',
            new_name='cliente_id',
        ),
        migrations.RenameField(
            model_name='despacho',
            old_name='aeronave',
            new_name='aeronave_id',
        ),
        migrations.RenameField(
            model_name='despacho',
            old_name='carga',
            new_name='carga_id',
        ),
        migrations.RenameField(
            model_name='despacho',
            old_name='conductor',
            new_name='conductor_id',
        ),
        migrations.RenameField(
            model_name='despacho',
            old_name='piloto',
            new_name='piloto_id',
        ),
        migrations.RenameField(
            model_name='despacho',
            old_name='ruta',
            new_name='ruta_id',
        ),
        migrations.RenameField(
            model_name='despacho',
            old_name='vehiculo',
            new_name='vehiculo_id',
        ),
    ]
